# Generated by Django 5.2.17 on 2026-09-26 23:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.CharField(blank=True, max_length=8)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('title', models.CharField(max_length=300)),
                ('cause', models.TextField(help_text='Why this alert appeared')),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.CharField(max_length=64)),
                ('dedupe_key', models.CharField(max_length=200)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('challenge_note', models.TextField(blank=True, help_text='Employee explanation or challenge')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='identity.membership')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.membership')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'resolved'), _negated=True), fields=('workspace', 'recipient', 'dedupe_key'), name='uniq_unresolved_alert')],
            },
        ),
        migrations.CreateModel(
            name='RuleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.TextField()),
                ('conditions', models.TextField()),
                ('action', models.TextField()),
                ('explanation', models.TextField()),
                ('params', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.membership')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.workspace')),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'code'), name='uniq_rule_code')],
            },
        ),
        migrations.CreateModel(
            name='RuleExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.CharField(max_length=8)),
                ('rule_version', models.PositiveIntegerField()),
                ('dedupe_key', models.CharField(max_length=200)),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.CharField(max_length=64)),
                ('action_taken', models.CharField(max_length=300)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'rule_code', 'dedupe_key'), name='uniq_rule_execution')],
            },
        ),
    ]
