# Generated by Django 5.2.17 on 2026-09-26 23:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('evidence_reference', models.CharField(max_length=300)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-received_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.CharField(max_length=64)),
                ('field', models.CharField(blank=True, max_length=60)),
                ('current_value', models.TextField(blank=True)),
                ('requested_value', models.TextField(blank=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='open', max_length=16)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='identity.membership')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.membership')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
