# Generated by Django 5.2.17 on 2026-09-26 23:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous', models.JSONField()),
                ('reason', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('email_normalized', models.CharField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=32)),
                ('linkedin_url', models.CharField(blank=True, max_length=300)),
                ('website', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(blank=True, help_text='ISO country used for phone normalisation', max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['company_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('confirmed', 'Confirmed')], default='previewed', max_length=16)),
                ('raw_csv', models.TextField()),
                ('headers', models.JSONField(default=list)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('errors_csv', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('source_reference', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('contacting', 'Contacting'), ('qualified', 'Qualified'), ('nurture', 'Nurture'), ('disqualified', 'Disqualified')], default='new', max_length=20)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('need', models.TextField(blank=True, help_text='Qualification: what they need')),
                ('fit', models.TextField(blank=True, help_text='Qualification: why we fit')),
                ('nurture_review_date', models.DateField(blank=True, null=True)),
                ('disqualify_reason', models.TextField(blank=True)),
                ('next_action', models.CharField(blank=True, max_length=300)),
                ('next_action_due', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('import_row', models.PositiveIntegerField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('service', models.CharField(blank=True, max_length=200)),
                ('stage', models.CharField(choices=[('discovery', 'Discovery'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='discovery', max_length=20)),
                ('stage_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, max_length=300)),
                ('next_action_due', models.DateTimeField(blank=True, null=True)),
                ('scope_reference', models.TextField(blank=True, help_text='Proposal / scope document reference')),
                ('lost_reason', models.TextField(blank=True)),
                ('commercial_decision', models.TextField(blank=True, help_text='Recorded commercial decision when won')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=20)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('from_stage', models.CharField(blank=True, max_length=20)),
                ('to_stage', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('linkedin', 'LinkedIn'), ('note', 'Note')], max_length=16)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('outcome', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verification', models.CharField(choices=[('self_reported', 'Self-reported'), ('provider_confirmed', 'Provider-confirmed')], default='self_reported', max_length=24)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('source_url', models.CharField(blank=True, max_length=300)),
                ('next_action', models.CharField(blank=True, max_length=300)),
                ('corrected', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='identity.membership')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
