# Generated by Django 5.2.17 on 2026-09-26 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('identity', '0001_initial'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='work.client'),
        ),
        migrations.AddField(
            model_name='activity',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='activityrevision',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='crm.activity'),
        ),
        migrations.AddField(
            model_name='activityrevision',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.membership'),
        ),
        migrations.AddField(
            model_name='activityrevision',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='contact',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='activity',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.membership'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='default_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.membership'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.membership'),
        ),
        migrations.AddField(
            model_name='lead',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.importbatch'),
        ),
        migrations.AddField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to='identity.membership'),
        ),
        migrations.AddField(
            model_name='lead',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_leads', to='identity.membership'),
        ),
        migrations.AddField(
            model_name='lead',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='activity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.membership'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_opportunities', to='identity.membership'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_opportunities', to='identity.membership'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.workspace'),
        ),
        migrations.AddField(
            model_name='activity',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.membership'),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.workspace'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('workspace', 'sha256'), name='uniq_import_file'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('import_batch', 'import_row'), name='uniq_lead_import_row'),
        ),
    ]
