# Generated by Django 5.2.17 on 2026-09-26 23:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_settings', serialize=False, to='identity.workspace')),
                ('enabled', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('mock', 'Offline test provider (no cost)'), ('anthropic', 'Anthropic Claude API')], default='mock', max_length=16)),
                ('model', models.CharField(default='claude-haiku-4-5', max_length=80)),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=8)),
                ('input_cost_per_mtok', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=8)),
                ('output_cost_per_mtok', models.DecimalField(decimal_places=4, default=Decimal('5.0000'), max_digits=8)),
                ('max_output_tokens', models.PositiveIntegerField(default=600)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(choices=[('summarize', 'Summarize notes'), ('draft_followup', 'Draft follow-up')], max_length=20)),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.CharField(max_length=64)),
                ('source_activity_ids', models.JSONField(default=list)),
                ('provider', models.CharField(max_length=16)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('ok', 'Completed'), ('disabled', 'AI disabled'), ('over_budget', 'Over budget'), ('failed', 'Provider failed')], max_length=16)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('user_decision', models.CharField(blank=True, help_text='accepted / edited / rejected', max_length=16)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.membership')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIBudgetMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('spent_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('reserved_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'month'), name='uniq_ai_month')],
            },
        ),
    ]
