# Generated by Django 5.2.17 on 2026-09-26 23:38

import datetime
import django.db.models.deletion
import django.utils.timezone
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=64)),
                ('work_start', models.TimeField(default=datetime.time(9, 0))),
                ('work_end', models.TimeField(default=datetime.time(18, 0))),
                ('work_days', models.CharField(default='0,1,2,3,4', help_text='Python weekday numbers, Monday=0', max_length=20)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'CEO / workspace owner'), ('admin', 'Workspace administrator'), ('sales_manager', 'Sales manager'), ('sales_rep', 'Sales representative'), ('delivery_manager', 'Delivery manager'), ('delivery_employee', 'Delivery employee')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=16)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('unavailable_until', models.DateField(blank=True, help_text='Approved leave: no automatic assignment until this date', null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, max_length=64)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='identity.workspace')),
            ],
            options={
                'ordering': ['user__first_name', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'CEO / workspace owner'), ('admin', 'Workspace administrator'), ('sales_manager', 'Sales manager'), ('sales_rep', 'Sales representative'), ('delivery_manager', 'Delivery manager'), ('delivery_employee', 'Delivery employee')], max_length=32)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.membership')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='identity.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=300)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.membership')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='uniq_membership'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['workspace', 'entity_type', 'entity_id'], name='identity_au_workspa_6965a1_idx'),
        ),
    ]
